### PR TITLE
Test CI: travis CI -> GitHub Actions

### PR DESCRIPTION
**Pull request by eggplants**
- delete: `.travis.yml`
- add: `.github/workflows/test.yml`

Test run: https://github.com/eggplants/sparqlwrapper/actions/runs/1651950750

### CODE REVIEW

**Comment by eggplants** [comment]
image

**Comment by eggplants** [comment]
`nose` is not working in Python 3.10 bue to `AttributeError: module 'collections' has no attribute 'Callable'`.

**Comment by aucampia** [comment]
> `nose` is not working in Python 3.10 due to `AttributeError: module 'collections' has no attribute 'Callable'`.

yes we did a huge overhaul on the main repo (https://github.com/RDFLib/rdflib) - will have to do same here.

**Comment by eggplants** [comment]
For continued development, I think we need to replace nosetests with pytests.

**Comment by aucampia** [comment]
that is what we did in https://github.com/RDFLib/rdflib - any PRs to do the same here will be welcome.

File: .github/workflows/test.yml [hunk 1]
```diff
@@ -0,0 +1,135 @@
+name: Test
+
+on:
```
Comment (aucampia) [inline .github/workflows/test.yml:3]: Our config for main repo is this:

https://github.com/RDFLib/rdflib/blob/6aefe60ecd1f4c0b069919d898b3ed42a2d9cd03/.github/workflows/validate.yaml#L3-L7

```
on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:
```

And it is maybe a bit more appropriate

File: .github/workflows/test.yml [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+      - '!gh-pages'
+  pull_request:
+    branches:
+      - '*'
+      - '*/*'
+      - '**'
+      - '!gh-pages'
+  workflow_dispatch:
+
+jobs:
```
Comment (aucampia) [inline .github/workflows/test.yml:18]: Please use a test matrix like this:

https://github.com/RDFLib/rdflib/blob/6aefe60ecd1f4c0b069919d898b3ed42a2d9cd03/.github/workflows/validate.yaml#L19-L27

Comment (eggplants) [reply .github/workflows/test.yml:18]: Parallel execution using the build matrix will result in concurrent API execution, which I think may be limited depending on the endpoint, so I'm using sequential execution.

Comment (aucampia) [reply .github/workflows/test.yml:18]: You can use this to control it: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency

Comment (eggplants) [reply .github/workflows/test.yml:18]: See:
https://github.com/Animenosekai/translate/pull/27

Comment (eggplants) [reply .github/workflows/test.yml:9]: I set `max-parallel: 1`. I cannot undertand how to do sequencial execution with `concurrency`.

**Comment by eggplants** [comment]
https://github.com/eggplants/sparqlwrapper/actions/runs/1653813870

**Comment by eggplants** [comment]
𝙍𝙚𝙖𝙙𝙮 𝙛𝙤𝙧 𝙧𝙚𝙫𝙞𝙚𝙬…

File: .github/workflows/test.yml [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+  test:
+    runs-on: ubuntu-latest
+    strategy:
+        fail-fast: false
+        max-parallel: 1
+        matrix:
+            python-version: ["3.7", "3.8", "3.9", "3.10"]
```
Comment (aucampia) [inline .github/workflows/test.yml:16]:
```suggestion
            python-version: ["3.7", "3.8", "3.9"]
```

3.10 is not expected to work yet (because of nose) so lets not add it until we know it passes. It may be a bit academic since the other tests are also failing, but at least they should be passing.

File: .github/workflows/test.yml [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+    steps:
+    - uses: actions/checkout@v2
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip setuptools
+        python -m pip install rdflib-jsonld
```
Comment (aucampia) [inline .github/workflows/test.yml:26]: Rather remove this, as we will be merging things which make this work with rdflib 6.x which has integrated rdflib-jsonld.

```suggestion
```

File: .github/workflows/test.yml [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        python setup.py sdist && pip install ./dist/*
+    - name: Test
+      run: |
+        python -m unittest test/*.py
```
Comment (aucampia) [inline .github/workflows/test.yml:31]:
```suggestion
        python -m nose test/
```

**Review by aucampia — COMMENTED** [review]
Changes look good, some minor suggestions, maybe we should not quite merge immediately, but I would be fine if we do, we may need a couple of iterations to get the CI in master back into shape.

**Comment by eggplants** [comment]
I confirmed I can test even I use unittest instead of nose. So I replace nose with unittest.

File: .github/workflows/test.yml (hunk 3 above)
Comment (eggplants) [reply .github/workflows/test.yml:16]: I confirmed I can test even I use unittest instead of nose. So I replace nose with unittest.

File: .github/workflows/test.yml (hunk 5 above)
Comment (eggplants) [reply .github/workflows/test.yml:31]: I confirmed I can test even I use unittest instead of nose. So I replace nose with unittest.

**Comment by nicholascar** [comment]
@eggplants so are you saying that if you reject those changes proposed by @aucampia and keep using unittest instead of nose then everything works fine? If so, we should stick with unittest here for now? I'm happy with that.

**Comment by eggplants** [comment]
@nicholascar Yes.

**Comment by nicholascar** [comment]
OK, well then let's merge in now and see if the actions work nicely. So I'll merge and we should put in another small PR after this one to test things out.

File: .github/workflows/test.yml (hunk 5 above)
Comment (aucampia) [reply .github/workflows/test.yml:30]: Okay great, was not sure.

**Comment by aucampia** [comment]
Looking at failure on master now, will make a PR to fix shortly.
